[heading]
PAGE_TITLE = "GSoC Week 8 and 9"
BLOG_TITLE = "GSoC Week 8 and 9: Taking a break"
DATE = "22 August 2022"

[content]
CONTENT = '''
This blog post is related to my <a href="https://summerofcode.withgoogle.com/programs/2022/projects/BrXiUNA2">GSoC 2022
project</a>.
<br>
<p>
I decided to take a break from my GSoC project for these two weeks, mainly because I was feeling a little burnt out from doing
work but also because college had started to ramp up and I did not really have the time or energy to invest into my 
project with all the assignments due.
<br><br>
In this time, I began to read the book 'Engineering a Compiler' by Cooper & Torczon, to learn
more about compiler development. While reading it, I learned (till now) about finite / pushdown automata theory and the
two different styles of semantic analysis, with the main topics of interest being LR(1) parser construction (generation
of canonical LR(1) items) and ad-hoc syntax directed translation.
<br><br>
While not a very important reason, I was also waiting for my parser to get merged into the 'AST-Generation' branch so that
I would be able to begin Part 2 of my GSoC project. Now that that has happened, I am able to work on it and hopefully
finish my project before the final review date. Unfortunately, my exams are due to start at the end of this month, so it
is hard to say just how much work I will be able to get done before them. After they end, I will have 9 days to finish
up the code before the review is due.
</p>
'''