CHAR ::= "a-zA-Z0-9"

string ::= re* EOF

re ::= basic
     | maybe
     | star
     | plus
     | group
     | or

basic ::= CHAR | "[" CHAR+ "]"
maybe ::= re "?"
star ::= re "*"
plus ::= re "+"
group ::= "(" re+ ")"
or ::= basic | group "|" basic | group